#!/bin/bash

bash_greeting() {
    if command -v tput > /dev/null && [ -n "$TERM" ] && [ "$TERM" != "dumb" ]; then
        term_width=$(tput cols)
        wrap_width=$term_width

        if [ "$term_width" -gt 35 ]; then
            tput cr
            shuf -n 1 "$HOME/Documents/hypaurora/assets/2BPraise.txt" | fmt -w "$wrap_width"
        fi
    fi
}
