#!/bin/bash

get_git_branch() {
    local branch
    branch=$(git branch 2>/dev/null | grep '^*' | cut -d' ' -f2-)
    if [ -n "$branch" ]; then
        echo " $branch"
    fi
}

RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
YELLOW="\[\033[0;33m\]"
BLUE="\[\033[0;34m\]"
PURPLE="\[\033[0;35m\]"
CYAN="\[\033[0;36m\]"
WHITE="\[\033[0;37m\]"
BLACK="\[\033[0;30m\]"

BRED="\[\033[1;31m\]"
BGREEN="\[\033[1;32m\]"
BYELLOW="\[\033[1;33m\]"
BBLUE="\[\033[1;34m\]"
BPURPLE="\[\033[1;35m\]"
BCYAN="\[\033[1;36m\]"
BWHITE="\[\033[1;37m\]"
BBLACK="\[\033[1;30m\]"

BOLD="\[\033[1m\]"
RESET="\[\033[0m\]"

if [ "$ANTIGRAVITY_AGENT" = "1" ]; then
    # A Simple Prompt for AI Agents
    PS1="$ "
elif [ -n "$TERMUX_VERSION" ]; then
    PS1=" $BLUE\W$RESET $YELLOW\$(get_git_branch)$RED\$ $RESET"
else
    PS1="[$GREEN\u$RESET@$GREEN\h $BLUE\W$RESET]$YELLOW\$(get_git_branch)$RED\$ $RESET"
fi
