#!/usr/bin/env bash

# Get data from eww variables
SSID=$(eww get ssid_for_prompt)
PASSWORD=$(eww get password_input)

eww close password_window

# Attempt to connect if credentials are not empty
if [ -n "$SSID" ] && [ -n "$PASSWORD" ]; then
    # Use printf to pipe password to nmcli
    printf "%s\n" "$PASSWORD" | nmcli --ask device wifi connect "$SSID"
fi

# Clean up and close all related windows
eww close "wifi_list_window"
eww update password_input=""
