#!/usr/bin/env bash

CURRENT_STATUS=$(playerctl loop)

if [ "$CURRENT_STATUS" == "None" ]; then
    playerctl loop Track
elif [ "$CURRENT_STATUS" == "Track" ]; then
    playerctl loop Playlist
else
    playerctl loop None
fi
