#!/usr/bin/env bash

# Function to get and format the current volume status as JSON
get_volume_status() {
    if command -v pactl &> /dev/null; then
        muted=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')
        if [ "$muted" == "yes" ]; then
            echo '{"status": "Muted", "percentage": 0}'
        else
            volume=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep -o '[0-9]*%' | head -n1 | sed 's/%//')
            echo "{\"status\": \"Unmuted\", \"percentage\": $volume}"
        fi
    else
        echo '{"status": "Unknown", "percentage": -1}'
    fi
}

# Initial output
get_volume_status

# Listen for changes and update
pactl subscribe | stdbuf -oL grep --line-buffered 'on source' | while read -r; do
    get_volume_status
done