preload = ~/.config/background

wallpaper {
    monitor = eDP-1
    path = ~/.config/background
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/background
    fit_mode = cover
}
