#!/bin/bash

# Destination directory
destination_dir="$HOME/Pictures/background"
destination_file="$destination_dir/background.png"
destination_ide_gnome_file="$destination_dir/background-ide-gnome.png"
destination_ide_hypr_file="$destination_dir/background-ide-hypr.png"

# Check if image is dark or light itself:
identify -verbose background-dark.png

temp_file="$HOME/.cache/temp_cropped.png"

# Check if ffmpeg is installed
if ! command -v ffmpeg &>/dev/null; then
	notify-send "Error" "ffmpeg is not installed. Please install ffmpeg."
	exit 1
fi

ffmpeg -i "$1" -vf "scale='if(gt(a,16/9),-1,1920)':'if(gt(a,16/9),1080,-1)',crop=1920:1080" -qscale:v 2 "$destination_file" -y
ffmpeg -i "$destination_file" -filter_complex "curves=all=0.05/0 0.55/0.45 1/0.95" "$destination_dir/background-dark.png" -y
ffmpeg -i "$destination_file" -filter_complex "curves=all=0/0.1 0.4/0.6 0.9/1" "$destination_dir/background-light.png" -y

ffmpeg -i "$destination_file" -filter_complex "crop=1892:1019:14:47" -y "$temp_file" # With waybar
# ffmpeg -i "$destination_file" -filter_complex "crop=1892:1052:14:14" -y "$temp_file" # Without waybar

ffmpeg -i "$destination_file" -filter_complex "crop=1920:1048:0:32" -y "$destination_ide_gnome_file"
ffmpeg -i "$temp_file" -filter_complex "gblur=sigma=14:steps=6" -y "$destination_ide_hypr_file"

if [[ "$DESKTOP_SESSION" == "gnome" ]]; then
	gsettings set org.gnome.desktop.background picture-uri "$destination_dir/background-light.png"
	gsettings set org.gnome.desktop.background picture-uri-dark "$destination_dir/background-dark.png"
fi
