#!/bin/bash

# Get the current proxy status
current_status=$(gsettings get org.gnome.system.proxy mode)

# Toggle the proxy status
if [ "$current_status" = "'none'" ]; then
    gsettings set org.gnome.system.proxy mode 'manual'
    notify-send -i 'network-vpn-symbolic' "Proxy Enabled" "System proxy has been turned on."
else
    gsettings set org.gnome.system.proxy mode 'none'
    notify-send -i 'network-vpn-disabled-symbolic' "Proxy Disabled" "System proxy has been turned off."
fi
