#!/bin/bash

# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
user_dirs=("$HOME/.local/bin" "$HOME/bin" "$HOME/.local/binary" "$HOME/.npm-global/bin")
for dir in "${user_dirs[@]}"; do
    [[ -d "$dir" && ":$PATH:" != *":$dir:"* ]] && PATH="$dir:$PATH"
done
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi

# Load custom bash completions
COMPLETIONS_DIR="$HOME/Documents/hypaurora/bash/completions"
if [[ -d "$COMPLETIONS_DIR" ]]; then
    for completion_file in "$COMPLETIONS_DIR"/*; do
        if [[ -f "$completion_file" ]]; then
            source "$completion_file"
        fi
    done
fi


set_proxy

if [[ -z "$ANTIGRAVITY_AGENT" || "$ANTIGRAVITY_AGENT" != 1 ]]; then
    bash_greeting
fi

unset rc